version: "3.9"

services:
  db:
    container_name: db
    networks:
      - library-net
    image: postgres:latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data

  back:
    container_name: back
    networks:
      - library-net
    build: ./library_back
    command: bash -c "python manage.py makemigrations && 
                      python manage.py migrate &&
                      gunicorn src.wsgi --bind 0.0.0.0:8000"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - db

  front:
    container_name: front
    networks:
      - library-net
    build: ./library_front
    command : bash -c "npm run build &&
                      npm install -g serve &&
                      serve -s build"
    volumes:
      - front_build:/front/build
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - back
    stdin_open: true

  nginx:
    container_name: nginx
    networks:
      - library-net
    image: nginx:latest
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - front_build:/var/www/front
    ports:
      - 80:8080
    depends_on:
      - back
      - front

volumes:
  front_build:

networks:
  library-net:
    driver: bridge
