version: "3.9"

services:
  db:
    container_name: db
    networks:
      - library-net
    image: postgres:latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data

  back:
    container_name: back
    networks:
      - library-net
    build: ./library_back
    command: bash -c "python manage.py makemigrations && 
                      python manage.py migrate &&
                      python manage.py runserver"
    volumes:
      - .:/back
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - db

networks:
  library-net:
    driver: bridge
