version: "3.9"

services:
  db:
    container_name: db
    networks:
      - library-net
    image: postgres:latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data

  back:
    container_name: back
    networks:
      - library-net
    build: ./library_back
    command: gunicorn src.wsgi --bind 0.0.0.0:8000
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - db

  front:
    container_name: front
    networks:
      - library-net
    build: ./library_front
    command : npm start
    volumes:
      - .:/front
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - back
    stdin_open: true

networks:
  library-net:
    driver: bridge
