version: "3.9"
services:
  db:
    networks:
      - library
    container_name: library_db
    image: postgres:latest
    restart: always
    ports: 
      - 5432:5432
    environment:
      POSTGRES_DB: library_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: 127.0.0.1
      POSTGRES_PORT: 5432
networks:
  library:
    driver: bridge