version: "3.9"

services:
  db:
    container_name: db
    image: postgres:latest
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  back:
    container_name: back
    build: ./library_back
    command: python manage.py makemigrations && python manage.py migrate && python manage.py runserver
    volumes:
      - .:/back
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST="db"
      - POSTGRES_PORT=5432
    depends_on:
      - db