name: Lint

on: [push]

jobs:
  front_eslint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./library_front

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 14.x
      uses: actions/setup-node@v3
      with:
        node-version: 14.x
    
    - name: Install Dependencies
      run: npm install

    - name: ESLint check
      run: npm run lint

  back_lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./library_back

    steps:
    - uses: actions/checkout@v1
    - uses: ricardochaves/python-lint@test
