name: Lint

on:
  workflow_run:
    workflows: [Build]
    types: [completed]

jobs:
  front_eslint:
    runs-on: ubuntu-latest

    steps:
      - name: ESLint check
        run: docker-compose run front bash -c "npm run test"

  back_lint:
    runs-on: ubuntu-latest

    steps:
      - name: Run lint
        run: docker-compose run front bash -c "npm run lint"
